[package]
name = "monomyth-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
authors.workspace = true

[[bin]]
name = "monomyth"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
dotenvy = { workspace = true }
monomyth-core = { workspace = true }
monomyth-gen = { workspace = true }
monomyth-knowledge = { workspace = true, features = ["acquire"] }
monomyth-llm = { workspace = true }
monomyth-text = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true, features = ["formatting", "macros"] }
tokio = { workspace = true }

[lints]
workspace = true
